from average_rating import *
from cart import *
from categories import *
from delivery_time import *
from pages import *
from recent_products import *
from related_products import *
from text import *
from topseller import *
from filter import *
from forsale import *
from featured import *
