# Generated by Django 5.1.5 on 2025-02-10 04:54

import lfs.core.fields.thumbs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20150428_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (400, 400)), upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='meta_title',
            field=models.CharField(default='<name>', max_length=100, verbose_name='Meta title'),
        ),
    ]
