from django.urls import path
import lfs.manage.manufacturers.views

urlpatterns = [
    path(
        "manufacturers",
        lfs.manage.manufacturers.views.ManageManufacturersView.as_view(),
        name="lfs_manage_manufacturers",
    ),
    path(
        "manufacturer/<int:id>/data",
        lfs.manage.manufacturers.views.ManufacturerDataView.as_view(),
        name="lfs_manage_manufacturer",
    ),
    path(
        "manufacturer/<int:id>/products/",
        lfs.manage.manufacturers.views.ManufacturerProductsView.as_view(),
        name="lfs_manage_manufacturer_products",
    ),
    path(
        "manufacturer/<int:id>/seo/",
        lfs.manage.manufacturers.views.ManufacturerSEOView.as_view(),
        name="lfs_manage_manufacturer_seo",
    ),
    path(
        "manufacturer/<int:id>/portlets/",
        lfs.manage.manufacturers.views.ManufacturerPortletsView.as_view(),
        name="lfs_manage_manufacturer_portlets",
    ),
    path(
        "manufacturer/<int:id>/view-by-id/",
        lfs.manage.manufacturers.views.ManufacturerViewByIDView.as_view(),
        name="lfs_manufacturer_by_id",
    ),
    path(
        "manufacturer/add/",
        lfs.manage.manufacturers.views.ManufacturerCreateView.as_view(),
        name="lfs_manage_add_manufacturer",
    ),
    path(
        "manufacturer/<int:id>/delete/",
        lfs.manage.manufacturers.views.ManufacturerDeleteView.as_view(),
        name="lfs_delete_manufacturer",
    ),
    path(
        "manufacturer/<int:id>/delete/confirm/",
        lfs.manage.manufacturers.views.ManufacturerDeleteConfirmView.as_view(),
        name="lfs_delete_manufacturer_confirm",
    ),
    path(
        "manufacturers/no",
        lfs.manage.manufacturers.views.NoManufacturersView.as_view(),
        name="lfs_manage_no_manufacturers",
    ),
    path(
        "manufacturers/ajax",
        lfs.manage.manufacturers.views.ManufacturersAjaxView.as_view(),
        name="lfs_manufacturers_ajax",
    ),
]
