# Generated by Django 5.1.5 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='module',
            field=models.CharField(blank=True, choices=[('lfs_paypal.processor.PayPalProcessor', 'PayPal'), ('lfs_sofortueberweisung.models.SofortUeberweisungPaymentMethodProcessor', 'sofortueberweisung.de'), ('lfs_paymill.models.PaymillPaymentMethodProcessor', 'Paymill')], max_length=100, verbose_name='Module'),
        ),
    ]
