# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_add_sums_up_to_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='sums_up',
            field=models.BooleanField(default=True, help_text='Sums up with other discounts/vouchers', verbose_name='Sums up'),
        ),
    ]
