# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseaddress",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=10, null=True, verbose_name="Zip code"),
        ),
    ]
