# Generated by Django 5.0.1 on 2024-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_auto_20171029_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseaddress",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="baseaddress",
            name="firstname",
            field=models.CharField(max_length=100, verbose_name="Firstname"),
        ),
        migrations.AlterField(
            model_name="baseaddress",
            name="lastname",
            field=models.CharField(max_length=100, verbose_name="Lastname"),
        ),
        migrations.AlterField(
            model_name="baseaddress",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="baseaddress",
            name="zip_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                verbose_name="Zip code",
            ),
        ),
    ]
