# Generated by Django 5.1.5 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_DeliveryTimeOrder_to_OrderDeliveryTime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='orderitempropertyvalue',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Value'),
        ),
    ]
