# Generated by Django 5.1.5 on 2025-03-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Submitted"),
                    (1, "Paid"),
                    (7, "Prepared"),
                    (2, "Sent"),
                    (3, "Closed"),
                    (4, "Canceled"),
                    (5, "Payment Failed"),
                    (6, "Payment Flagged"),
                    (7, "Rating Mail senden"),
                    (8, "Vorbereitet"),
                    (9, "Bearbeitet"),
                ],
                default=0,
                verbose_name="State",
            ),
        ),
    ]
