# Generated by Django 5.1.5 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_add_sums_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheroptions',
            name='number_letters',
            field=models.CharField(blank=True, default='ABCDEFGHIJKLMNOPQRSTUVWXYZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='voucheroptions',
            name='number_prefix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucheroptions',
            name='number_suffix',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
