# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['qm', 'qm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Paket(e)', 'Paket(e)'], ['St\xfcck', 'St\xfcck']], max_length=30, verbose_name='Base price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_unit_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['qm', 'qm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Paket(e)', 'Paket(e)'], ['St\xfcck', 'St\xfcck']], max_length=30, verbose_name='Packing unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_calculator',
            field=models.CharField(blank=True, choices=[[b'lfs.gross_price.calculator.GrossPriceCalculator', 'Price includes tax'], [b'lfs.net_price.calculator.NetPriceCalculator', 'Price excludes tax']], max_length=255, null=True, verbose_name='Price calculator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['qm', 'qm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Paket(e)', 'Paket(e)'], ['St\xfcck', 'St\xfcck']], max_length=20, verbose_name='Price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['qm', 'qm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Paket(e)', 'Paket(e)'], ['St\xfcck', 'St\xfcck']], max_length=20, verbose_name='Quantity field unit'),
        ),
    ]
