# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170204_2050'),
        ('catalog', '0002_auto_20150427_2206'),
    ]

    operations = [
    ]
