# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 04:55
from __future__ import unicode_literals

from django.db import migrations


def update_price_calculator(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.filter(price_calculator="lfs.net_price.NetPriceCalculator"):
        product.price_calculator = "lfs.net_price.calculator.NetPriceCalculator"
        product.save()

    for product in Product.objects.filter(price_calculator="lfs.gross_price.GrossPriceCalculator"):
        product.price_calculator = "lfs.gross_price.calculator.GrossPriceCalculator"
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170214_1643'),
    ]

    operations = [
        migrations.RunPython(update_price_calculator),
    ]
