# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-04-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import lfs.core.fields.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170216_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytime',
            name='description_internal',
            field=models.TextField(blank=True, verbose_name='Description Internal'),
        ),
    ]
