# Generated by Django 5.1.5 on 2025-02-10 04:54

import django.db.models.deletion
import lfs.core.fields.thumbs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170216_0455'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)), upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(default='<name>', max_length=100, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Category with products'), (1, 'Category with subcategories')], null=True, verbose_name='Category template'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='contenttypes.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)), upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price_unit',
            field=models.CharField(blank=True, choices=[('100g', '100g'), ('100 Stück', '100 Stück'), ('Anwendungen', 'Anwendungen'), ('cbm', 'cbm'), ('Gebinde', 'Gebinde'), ('hl', 'hl'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('ml', 'ml'), ('Paket(e)', 'Paket(e)'), ('qm', 'qm'), ('t', 't'), ('lfm', 'lfm'), ('Stück', 'Stück')], max_length=30, verbose_name='Base price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default='<name>', max_length=80, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_unit_unit',
            field=models.CharField(blank=True, choices=[('100g', '100g'), ('100 Stück', '100 Stück'), ('Anwendungen', 'Anwendungen'), ('cbm', 'cbm'), ('Gebinde', 'Gebinde'), ('hl', 'hl'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('ml', 'ml'), ('Paket(e)', 'Paket(e)'), ('qm', 'qm'), ('t', 't'), ('lfm', 'lfm'), ('Stück', 'Stück')], max_length=30, verbose_name='Packing unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.product', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_calculator',
            field=models.CharField(blank=True, choices=[('lfs.gross_price.calculator.GrossPriceCalculator', 'Price includes tax'), ('lfs.net_price.calculator.NetPriceCalculator', 'Price excludes tax'), ('lfs_bulk_prices.calculator.BulkPricesCalculator', 'Bulk prices calculator')], max_length=255, null=True, verbose_name='Price calculator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('100g', '100g'), ('100 Stück', '100 Stück'), ('Anwendungen', 'Anwendungen'), ('cbm', 'cbm'), ('Gebinde', 'Gebinde'), ('hl', 'hl'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('ml', 'ml'), ('Paket(e)', 'Paket(e)'), ('qm', 'qm'), ('t', 't'), ('lfm', 'lfm'), ('Stück', 'Stück')], max_length=20, verbose_name='Price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.CharField(choices=[('0', 'Standard'), ('1', 'Product with variants'), ('2', 'Variant'), ('3', 'Configurable product')], default='0', max_length=10, verbose_name='Subtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='template',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Default')], null=True, verbose_name='Product template'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('100g', '100g'), ('100 Stück', '100 Stück'), ('Anwendungen', 'Anwendungen'), ('cbm', 'cbm'), ('Gebinde', 'Gebinde'), ('hl', 'hl'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('ml', 'ml'), ('Paket(e)', 'Paket(e)'), ('qm', 'qm'), ('t', 't'), ('lfm', 'lfm'), ('Stück', 'Stück')], max_length=20, verbose_name='Quantity field unit'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='catalog.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
