# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lfs.core.fields.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170216_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)), upload_to=b'images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='static_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.StaticBlock', verbose_name='Static block'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (300, 300), (400, 400), (600, 600)), upload_to=b'images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Package(s)', 'Package(s)'], ['Piece(s)', 'Piece(s)']], max_length=30, verbose_name='Base price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_unit_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Package(s)', 'Package(s)'], ['Piece(s)', 'Piece(s)']], max_length=30, verbose_name='Packing unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_calculator',
            field=models.CharField(blank=True, choices=[['lfs.gross_price.calculator.GrossPriceCalculator', 'Price includes tax'], ['lfs.net_price.calculator.NetPriceCalculator', 'Price excludes tax']], max_length=255, null=True, verbose_name='Price calculator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Package(s)', 'Package(s)'], ['Piece(s)', 'Piece(s)']], max_length=20, verbose_name='Price unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='static_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.StaticBlock', verbose_name='Static block'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[['l', 'l'], ['m', 'm'], ['cm', 'cm'], ['lfm', 'lfm'], ['Package(s)', 'Package(s)'], ['Piece(s)', 'Piece(s)']], max_length=20, verbose_name='Quantity field unit'),
        ),
    ]
