# Generated by Django 5.1.5 on 2025-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_image_alter_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Your unique article number of the product.', max_length=40, verbose_name='SKU'),
        ),
    ]
