# Generated by Django 5.1.5 on 2025-02-21 11:33

from django.db import migrations, models

from lfs.catalog.models import LFS_BASE_PRICE_UNITS, LFS_PACKING_UNITS, LFS_PRICE_UNITS, LFS_UNITS


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="base_price_unit",
            field=models.CharField(
                blank=True,
                choices=LFS_BASE_PRICE_UNITS,
                default="",
                max_length=30,
                verbose_name="Base price unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="packing_unit_unit",
            field=models.CharField(
                blank=True,
                choices=LFS_PACKING_UNITS,
                default="",
                max_length=30,
                verbose_name="Packing unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="template",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Default template"), (1, "Default template")],
                null=True,
                verbose_name="Product template",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_unit",
            field=models.CharField(
                blank=True,
                choices=LFS_PRICE_UNITS,
                max_length=20,
                verbose_name="Price unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=LFS_UNITS,
                max_length=20,
                verbose_name="Quantity field unit",
            ),
        ),
    ]
