# Generated by Django 5.1.5 on 2025-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_base_price_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="modification_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modification date"),
        ),
    ]
