# Generated by Django 5.1.5 on 2025-02-27 11:31

from django.db import migrations


def copy_product_modification_date(apps, schema_editor):
    """
    Copies the modification date from the old holzimgarten_app
    """
    try:
        HIG = apps.get_model("holzimgarten_app", "ProductMetaData")
    except LookupError:
        return

    HEO = apps.get_model("catalog", "Product")

    for p in HEO.objects.all():
        try:
            pmd = HIG.objects.get(product=p)
        except HIG.DoesNotExist:
            HEO.objects.filter(id=p.id).update(modification_date=p.creation_date)
        else:
            HEO.objects.filter(id=p.id).update(modification_date=pmd.modification_date)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_modification_date"),
    ]

    operations = [
        migrations.RunPython(copy_product_modification_date),
    ]
