# Generated by Django 5.1.5 on 2025-03-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_auto_20250227_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="Unit"
            ),
        ),
    ]
