# Generated by Django 5.1.5 on 2025-03-04 09:02

import lfs.core.fields.thumbs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_property_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=lfs.core.fields.thumbs.ImageWithThumbsField(
                blank=True,
                max_length=120,
                null=True,
                sizes=(
                    (60, 60),
                    (100, 100),
                    (200, 200),
                    (300, 300),
                    (400, 400),
                    (600, 600),
                ),
                upload_to="images",
                verbose_name="Image",
            ),
        ),
    ]
