# Generated by Django 5.1.5 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="template",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Default")],
                null=True,
                verbose_name="Product template",
            ),
        ),
    ]
