# Generated by Django 5.1.5 on 2025-09-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_product_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="static_block",
            new_name="static_block_above",
        ),
    ]
