# Generated by Django 5.1.5 on 2025-09-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_rename_static_block_to_static_block_above"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="static_block_above",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_above",
                to="catalog.staticblock",
                verbose_name="Static block Above",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="static_block_below",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_below",
                to="catalog.staticblock",
                verbose_name="Static block Below",
            ),
        ),
    ]
