# Generated by Django 5.2.12 on 2026-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_add_static_block_below_and_alter_static_block_above"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active_packing_unit",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, verbose_name="Active packing"
            ),
        ),
    ]
