# Generated by Django 5.1.5 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20170216_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='price_calculator',
            field=models.CharField(choices=[('lfs.shipping.calculator.GrossShippingMethodPriceCalculator', 'Price includes tax'), ('lfs.shipping.calculator.NetShippingMethodPriceCalculator', 'Price excludes tax'), ('holzimgarten_app.shipping.HiGShippingMethodPriceCalculator', 'HIG')], default='lfs.shipping.calculator.GrossShippingMethodPriceCalculator', max_length=200, verbose_name='Price Calculator'),
        ),
    ]
