# Generated by Django 5.1.5 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0003_alter_shippingmethod_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="price_calculator",
            field=models.CharField(
                choices=[
                    (
                        "lfs.shipping.calculator.GrossShippingMethodPriceCalculator",
                        "Price includes tax",
                    ),
                    (
                        "lfs.shipping.calculator.NetShippingMethodPriceCalculator",
                        "Price excludes tax",
                    ),
                    (
                        "hig_shipping_calculator.calculator.HIGShippingMethodPriceCalculator",
                        "HIG",
                    ),
                ],
                default="lfs.shipping.calculator.GrossShippingMethodPriceCalculator",
                max_length=200,
                verbose_name="Price Calculator",
            ),
        ),
    ]
