# Generated by Django 5.1.5 on 2025-02-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='export.script', verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='method',
            field=models.CharField(default='export', max_length=100),
        ),
        migrations.AlterField(
            model_name='script',
            name='module',
            field=models.CharField(default='lfs.export.generic', max_length=100),
        ),
    ]
