# Generated by Django 5.1.5 on 2025-02-10 04:54

import lfs.core.fields.thumbs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170216_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=lfs.core.fields.thumbs.ImageWithThumbsField(blank=True, null=True, sizes=((60, 60), (100, 100), (200, 200), (400, 400)), upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='meta_title',
            field=models.CharField(blank=True, default='<name>', max_length=80, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price_calculator',
            field=models.CharField(choices=[('lfs.gross_price.calculator.GrossPriceCalculator', 'Price includes tax'), ('lfs.net_price.calculator.NetPriceCalculator', 'Price excludes tax'), ('lfs_bulk_prices.calculator.BulkPricesCalculator', 'Bulk prices calculator')], default='lfs.gross_price.calculator.GrossPriceCalculator', max_length=255, verbose_name='Price calculator'),
        ),
    ]
