from django.urls import path
import lfs.manage.categories.views

urlpatterns = [
    path(
        "categories",
        lfs.manage.categories.views.ManageCategoriesView.as_view(),
        name="lfs_manage_categories",
    ),
    path(
        "category/<int:id>/",
        lfs.manage.categories.views.CategoryDataView.as_view(),
        name="lfs_manage_category",
    ),
    path(
        "category/<int:id>/view/",
        lfs.manage.categories.views.CategoryViewView.as_view(),
        name="lfs_manage_category_view",
    ),
    path(
        "category/<int:id>/products/",
        lfs.manage.categories.views.CategoryProductsView.as_view(),
        name="lfs_manage_category_products",
    ),
    path(
        "category/<int:id>/seo/",
        lfs.manage.categories.views.CategorySEOView.as_view(),
        name="lfs_manage_category_seo",
    ),
    path(
        "category/<int:id>/portlets/",
        lfs.manage.categories.views.CategoryPortletsView.as_view(),
        name="lfs_manage_category_portlets",
    ),
    path(
        "category/<int:id>/view-by-id/",
        lfs.manage.categories.views.CategoryViewByIDView.as_view(),
        name="lfs_category_by_id",
    ),
    path(
        "category/add/",
        lfs.manage.categories.views.CategoryCreateView.as_view(),
        name="lfs_manage_add_top_category",
    ),
    path(
        "category/<int:parent_id>/add/",
        lfs.manage.categories.views.CategoryCreateView.as_view(),
        name="lfs_manage_add_category",
    ),
    path(
        "category/<int:id>/delete/",
        lfs.manage.categories.views.CategoryDeleteView.as_view(),
        name="lfs_delete_category",
    ),
    path(
        "category/<int:id>/delete/confirm/",
        lfs.manage.categories.views.CategoryDeleteConfirmView.as_view(),
        name="lfs_delete_category_confirm",
    ),
    path(
        "categories/no",
        lfs.manage.categories.views.NoCategoriesView.as_view(),
        name="lfs_manage_no_categories",
    ),
    path(
        "sort-categories",
        lfs.manage.categories.views.SortCategoriesView.as_view(),
        name="lfs_sort_categories",
    ),
]
