# Generated by Django 5.1.5 on 2025-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitempropertyvalue',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Value'),
        ),
    ]
