# django imports
from django.utils.translation import gettext_lazy as _

CATEGORY_VARIANTS_NONE = 0
CATEGORY_VARIANTS_DEFAULT = 1
CATEGORY_VARIANTS_CHEAPEST = 2
CATEGORY_VARIANTS_ALL = 3

CATEGORY_VARIANTS_CHOICES = (
    (CATEGORY_VARIANTS_NONE, _("---")),
    (CATEGORY_VARIANTS_DEFAULT, _("Default")),
    (CATEGORY_VARIANTS_CHEAPEST, _("Cheapest")),
    (CATEGORY_VARIANTS_ALL, _("All")),
)
